version: '3'

services:
  notes-app-client:
    container_name: notes-app-client
    image: node:alpine
    volumes:
      - ./client:/app
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - '5173:5173'
  notes-app-server:
    container_name: notes-app-server
    image: node:alpine
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev"
    volumes:
      - ./server:/app
    ports:
      - '8080:8080'
    environment:
      - PORT=${PORT}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - notes-app-db
  notes-app-db:
    container_name: notes-app-db
    image: 'postgres:14-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: {}
