version: '3.8'

services:
  notes-app-server:
    container_name: notes-app-server
    image: node:alpine
    working_dir: /app
    command: sh -c 'yarn && yarn dev'
    volumes:
      - ./server:/app
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - notes-app-db
  notes-app-db:
    container_name: notes-app-db
    image: 'postgres:14-alpine'
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: {}
