version: '3'

services:
  notes-app-client:
    container_name: notes-app-client
    image: node:alpine
    volumes:
      - ./client:/app
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - '5173:5173'
  notes-app-server:
    container_name: notes-app-server
    image: node:alpine
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev"
    volumes:
      - ./server:/app
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=notes_app_database
      - DB_HOST=notes-app-db
    depends_on:
      - notes-app-db
  notes-app-db:
    container_name: notes-app-db
    image: 'postgres:14-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes_app_database
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: {}